### ISSUE TITLE
Add - Background SVG

### ISSUE THREAD

**Issue by saboyadev** [SaboyaDev/manage-company-landing-page#7]
# Designs Desktop - Mobile 
<img  width="300" alt="Screen Shot 2023-06-03 at 1 25 12 PM" src="https://github.com/SaboyaDev/manage-company-landing-page/assets/16430662/b1bb6cff-9aeb-4f24-a491-b1806bec3aab">

<img width="114" alt="Screen Shot 2023-06-03 at 1 25 28 PM" src="https://github.com/SaboyaDev/manage-company-landing-page/assets/16430662/623135b8-f0b0-4e1c-8447-28b747c1ae00">

**Comment by SaboyaDev** [comment]
# Designs Desktop - Mobile 
<img  width="300" alt="Screen Shot 2023-06-03 at 1 25 12 PM" src="https://github.com/SaboyaDev/manage-company-landing-page/assets/16430662/b1bb6cff-9aeb-4f24-a491-b1806bec3aab">

<img width="114" alt="Screen Shot 2023-06-03 at 1 25 28 PM" src="https://github.com/SaboyaDev/manage-company-landing-page/assets/16430662/623135b8-f0b0-4e1c-8447-28b747c1ae00">

**Comment by saboyadev** [comment]
- [ ] Add SVG Background

**Comment by saboyadev** [comment]
Looks like the Background SVG should be placed within a page wrapper that has a container TailwindCSS utility class.
